-- Adds the seven groups that appear in the 2026-08-12 Student Interest Group
-- form export ("Student Interest Group 8.12.26.xlsx") and were not already on
-- the site.
--
-- Run in the Supabase SQL editor -- writes are blocked for the anon key by RLS.
-- INSERT-only with ON CONFLICT DO NOTHING, so it never touches an existing row
-- and is safe to re-run. Generated from uploads/clubs.json, which stays the
-- source of truth.
--
-- Column types differ between the two array-ish columns, so the casts are not
-- interchangeable: `interests` is text[] (write ARRAY[...]::text[]) while
-- `scores` is jsonb (write '{...}'::jsonb).
--
-- `photos` is deliberately left out of the column list: none of these groups
-- has photos yet, and the app already guards on Array.isArray(club.photos), so
-- the column default is fine.
--
-- Two sponsors are not confirmed yet -- the form listed "Riley Davis (TBD)" for
-- the Computer Science Group and "Pegge Fox (not 100% confirmed yet)" for Data
-- Science & AI, and Wayzata Immune gave last year's advisor, Molly Davin. The
-- names are stored plain; update them once the sponsors are settled.
--
-- Student leader names are collected by the form but deliberately not stored
-- (no column, and they go stale yearly), and no phone numbers are stored at all
-- -- see update-form-submissions-2.sql.
-- Generated 2026-08-12.

begin;

insert into clubs (
  id, name, category, advisor, description,
  target_audience, detailed_description,
  meeting_location, meeting_days, meeting_time, is_student_led,
  interests, scores, instagram, email, phone
) values
  ('data-science-and-ai', 'Data Science & AI', 'CTE', 'Pegge Fox', 'Wayzata Data Science & AI group explores machine learning, data analysis, and real-world AI applications through hands-on projects, competitions, and guest speakers.', 'Students interested in data science, machine learning, and AI.', 'Data Science & AI explores machine learning, data analysis, and real-world AI applications through hands-on projects, competitions, and guest speakers.', 'Ms. Fox''s room', 'Every other Wednesday', 'After school, 3:10-4:10 p.m.', true, ARRAY['Machine learning', 'Data analysis', 'Real-world AI applications', 'Hands-on projects', 'Competitions', 'Guest speakers']::text[], '{"science_stem": 3, "arts_creative": 0, "health_medical": 0, "competitiveness": 2, "time_commitment": 2, "world_languages": 0, "trades_technical": 0, "community_service": 0, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 4, "academic_competition": 2, "computer_science_tech": 5, "leadership_government": 0, "leadership_opportunity": 1, "social_special_interest": 1, "public_speaking_emphasis": 0, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'soodabh000@isd284.com', null),
  ('environmental-group', 'Environmental Group', 'Service & Leadership', 'Elyssa McIntyre', 'Educational group to learn about the environment together and participate in sustainable/conservation activities.', 'Students interested in the environment and conservation.', 'Environmental Group is an educational group where students learn about the environment together and take part in sustainability and conservation activities.', 'A417', 'Before or after school on Wednesdays, 1-2 times a month', 'Before school, 7:40-8:10 a.m.', true, ARRAY['Environmental education', 'Sustainability', 'Conservation activities', 'Hands-on learning']::text[], '{"science_stem": 2, "arts_creative": 0, "health_medical": 0, "competitiveness": 0, "time_commitment": 1, "world_languages": 0, "trades_technical": 0, "community_service": 3, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 3, "academic_competition": 0, "computer_science_tech": 0, "leadership_government": 0, "leadership_opportunity": 1, "social_special_interest": 2, "public_speaking_emphasis": 0, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 5}'::jsonb, null, 'ostraoli000@isd284.com', null),
  ('leaders-and-lawmakers', 'Leaders and Lawmakers', 'Service & Leadership', 'Amanda Campbell', 'A space where students can practice their leadership skills in so many different ways including public speaking and digging deeper on what being a lawyer and working in the field might mean for them.', 'Students interested in leadership, public speaking, and law careers.', 'Leaders and Lawmakers is a space where students practice leadership skills in many different ways, including public speaking, and dig deeper into what being a lawyer and working in the field might mean for them.', 'A418', 'Every other Wednesday', 'After school, 3:10-4:10 p.m.', true, ARRAY['Leadership skills', 'Public speaking', 'Law careers', 'Exploring the legal field']::text[], '{"science_stem": 0, "arts_creative": 0, "health_medical": 0, "competitiveness": 0, "time_commitment": 2, "world_languages": 0, "trades_technical": 0, "community_service": 0, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 3, "academic_competition": 0, "computer_science_tech": 0, "leadership_government": 4, "leadership_opportunity": 4, "social_special_interest": 1, "public_speaking_emphasis": 5, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'goldbsho000@isd284.com', null),
  ('wayzata-computer-science-group', 'Wayzata Computer Science Group', 'CTE', 'Riley Davis', 'We get together weekly and teach member computer science topics. We focus on Python primarily during the beginning of the year and do fun projects that help them apply their learning. We foster teamwork with goals of incorporating group projects and team hackathons. Later in the year we are planning to introduce many other computer science aspects and fields like machine learning, cybersecurity, web developments, and agentic uses of artificial intelligence. The goal of these introductory lessons later in the year is to spark curiosity and set members up so that they can dive deeper into these topics themselves if they believe it is a topic of interest or a future career. We are hoping to get a guest speaker or two to let members get a real word understanding of how computer science is still being applied, but that part hasn''t been figured out yet. We''ve been a club for many years but this year are hoping to do more then ever before for our members.', 'Students interested in coding and computer science careers.', 'Wayzata Computer Science Group meets weekly to teach members computer science topics, focusing on Python early in the year with fun projects that apply what members learn. It fosters teamwork through group projects and team hackathons, and later in the year introduces other computer science fields such as machine learning, cybersecurity, web development, and agentic uses of artificial intelligence, so members can dive deeper into whichever topics interest them as a possible career.', 'A144 in 1st Floor New A', 'Wednesdays', 'After school, 3:10-4:10 p.m.', true, ARRAY['Python programming', 'Group projects', 'Team hackathons', 'Machine learning', 'Cybersecurity', 'Web development', 'Artificial intelligence']::text[], '{"science_stem": 3, "arts_creative": 0, "health_medical": 0, "competitiveness": 1, "time_commitment": 3, "world_languages": 0, "trades_technical": 0, "community_service": 0, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 4, "academic_competition": 1, "computer_science_tech": 5, "leadership_government": 0, "leadership_opportunity": 2, "social_special_interest": 2, "public_speaking_emphasis": 1, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'nayakary000@isd284.com', null),
  ('wayzata-immune', 'Wayzata Immune', 'CTE', 'Molly Davin', 'Improve health literacy and educate students on the immune system and public health', 'Students interested in public health and the immune system.', 'Wayzata Immune works to improve health literacy and educate students on the immune system and public health.', 'A213', 'Once a month, typically on a Tuesday', 'After school, 3:10-4:10 p.m.', true, ARRAY['Health literacy', 'Immune system', 'Public health', 'Health education']::text[], '{"science_stem": 3, "arts_creative": 0, "health_medical": 5, "competitiveness": 0, "time_commitment": 1, "world_languages": 0, "trades_technical": 0, "community_service": 2, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 3, "academic_competition": 0, "computer_science_tech": 0, "leadership_government": 0, "leadership_opportunity": 1, "social_special_interest": 1, "public_speaking_emphasis": 1, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'karukadh000@isd284.com', null),
  ('wayzata-neuroscience', 'Wayzata Neuroscience', 'CTE', 'Gretchen Minnick', 'The purpose of this group is to help students learn more about the importance of neurology, while also providing interactive social events and opportunities for them to excel in.', 'Students interested in neuroscience and medicine.', 'Wayzata Neuroscience helps students learn more about the importance of neurology, while also providing interactive social events and opportunities for them to excel in.', 'C405', 'Last Friday of the month', 'After school, 3:10-4:10 p.m.', true, ARRAY['Neurology', 'Brain science', 'Interactive social events', 'Medicine careers']::text[], '{"science_stem": 4, "arts_creative": 0, "health_medical": 5, "competitiveness": 0, "time_commitment": 1, "world_languages": 0, "trades_technical": 0, "community_service": 0, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 3, "academic_competition": 0, "computer_science_tech": 0, "leadership_government": 0, "leadership_opportunity": 1, "social_special_interest": 2, "public_speaking_emphasis": 1, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'shajan000@isd284.com', null),
  ('wayzata-philosophy', 'Wayzata Philosophy', 'Service & Leadership', 'Elyssa McIntyre', 'The purpose of our group is to engage in discussion about the whys of life and get to know a deeper sense of self and personal identity through educational and conversational meetings based philosophical topics.', 'Students who enjoy open discussion about life, meaning, and identity.', 'Wayzata Philosophy engages students in discussion about the whys of life, building a deeper sense of self and personal identity through educational and conversational meetings on philosophical topics.', 'A417', 'Bi-monthly', 'After school, 3:10-4:10 p.m.', true, ARRAY['Philosophical discussion', 'The big questions of life', 'Personal identity', 'Self-reflection']::text[], '{"science_stem": 0, "arts_creative": 0, "health_medical": 0, "competitiveness": 0, "time_commitment": 1, "world_languages": 0, "trades_technical": 0, "community_service": 0, "cultural_identity": 0, "sports_recreation": 0, "team_vs_individual": 3, "academic_competition": 0, "computer_science_tech": 0, "leadership_government": 0, "leadership_opportunity": 1, "social_special_interest": 4, "public_speaking_emphasis": 3, "writing_media_journalism": 0, "business_entrepreneurship": 0, "environmental_sustainability": 0}'::jsonb, null, 'zehndnol000@isd284.com', null)
on conflict (id) do nothing;

commit;

-- Verify: expect 80 existing + 7 new = 87 total, matching uploads/clubs.json.
select count(*) as total_clubs from clubs;
select id, name, category from clubs
where id in (
  'data-science-and-ai', 'environmental-group', 'leaders-and-lawmakers',
  'wayzata-computer-science-group', 'wayzata-immune', 'wayzata-neuroscience',
  'wayzata-philosophy'
) order by id;
